### ISSUE TITLE
GraphQLBoolean needed

### ISSUE THREAD

**Issue by vronic** [xanthous-tech/grpc-graphql-schema#2]
in src/types.ts (GRPC_GQL_TYPE_MAPPING) need map to bool
bool: GraphQLBoolean

**Comment by neilbaylor** [comment]
I think you forgot to build the /lib directory before publishing to NPM

**Comment by Necmttn** [comment]
> I think you forgot to build the /lib directory before publishing to NPM

version 0.0.9 published.
